### ISSUE TITLE
Encapsulate logic of cluster and thread worker/pool

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#111]
**Is your feature request related to a problem? Please describe.**
With #66 we provided a new variant of pool.
Now we have very much duplicate code.
We need to find out what could be encapsulated into abstract classes and interfaces.

**Describe the solution you'd like**
- Create a abstract Pool and Worker definition that encapsulates some of the duplicate logic
- Define generic interfaces (e.g. for _InputOptions_) so you can easily exchange a thread pool with a cluster pool and vice versa.

**Comment by jerome-benoit** [comment]
Proposals: 

1. A worker proxy class can be created that will hide the worker type internal handling. The downside it that branching will be added to code path that can be performance sensitive. 
2. Composite design pattern: an abstract class define the expected worker API and inherited worker classes implement it. The instantiation is done at the the inherited classes level.
3. Strategy design pattern: a worker interface and a worker context. I do not think that fits for worker abstraction. But really fits well for pool abstraction: a pool interface and a pool context where we can dynamically choose things like worker choice strategy (I would like to add a last used algo), the kind of pool strategy, etc.

**Comment by pioardi** [comment]
Yes @jerome-benoit I think that for pool the option 3 forse really well. We could put an abstract classe in the middle if we feel Is needed.

For worker I need to think about it
