### ISSUE TITLE
De-duplicate Dynamic[Cluster/Thread]Pool chooseWorker with an implementation of the strategy design pattern

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#122]
**Is your feature request related to a problem? Please describe.**
Currently we have many LOC duplicated in these both `chooseWorker` functions

**Describe the solution you'd like**
Find a strategy to de duplicate this part of code and apply it

**Additional context**
https://github.com/pioardi/poolifier/pull/116#discussion_r574106019  
https://github.com/pioardi/poolifier/pull/116#issuecomment-777469240

---

A first try:

```ts
type IDynamicPool<Worker extends IWorker, Data, Response> = (
  | DynamicClusterPool<Data, Response>
  | DynamicThreadPool<Data, Response>
) &
  AbstractPool<Worker, Data, Response>

export function dynamicWorkerChooser<
  Worker extends IWorker,
  Data,
  Response,
  DynamicPool extends IDynamicPool<Worker, Data, Response>
> (this: DynamicPool, superChooseWorker: () => Worker): Worker {
  // ...
```

And then it could be called e.g. like this:
```ts
return dynamicWorkerChooser.bind(this, () => super.chooseWorker())
```

But when accessing functions like `internalNewWorker` or `sendToWorker` in `this(: DynamicPool)`, it cannot access them, because it tells me that `this` has no method defined like the ones :confused:

**Comment by Shinigami92** [comment]
As proposed by @jerome-benoit [#116 comment(589046613)](https://github.com/pioardi/poolifier/pull/116#pullrequestreview-589046613)  
We could let `Dynamic_X_Pool` extend directly from `AbstractPool` and then have a `Fixed_X_Pool` as composition in it  
But I think that this would mean that we need to forward many member functions to its composition :thinking:

**Comment by Shinigami92** [comment]
IMO we have a diamond inheritance problem here :slightly_frowning_face: 

# Currently Implementation

## Pros

- Logic for Thread is shared
- Logic for Cluster is shared

## Cons

- Duplicate code in Dynamic Pools


![By Dynamic based on Fixed - Class Diagram](https://www.planttext.com/api/plantuml/img/TP1D3i9028Ntd88BU8Tg6zSkl02T8Jh9_2H0a_RsZdKMEgaxU7oyHnZKI6n94S22HSRBXjEMAGM7CobxB1clOQt52ST8gZW5UWWb0A1PJSWPkdrmRksjb6htqVRL-rEO_5j6NespxzWlT8oB6ij_ji7jnWFdBl6NFxBlSm66gjUNl000)

---

# Cluster/Thread - Class Diagram

## Pros

- Logic for Thread and Cluster are separated from each other

## Cons

- Duplicate Code for Fixed and Dynamic Pools

![Cluster/Thread - Class Diagram](https://www.planttext.com/api/plantuml/img/XP1H2i8m38RVSufSGBp2nE6p3ruWjc4MsWsI3ERjhRQmANDxp9SlVq8QDH8RKmImO97n74SrbkFj8KmU3ncGAhQ1Eg4407HN4tA6xjCurV8w33cZi3Bx9iYJSUz_j6BLJV-rwbt2n7ubSaPLR9yzfU2srMNesWKBzXsx9qEJKNxa2m00)

---

# Fixed/Dynamic - Class Diagram

## Pros

- Logic for Fixed is defined without the knowing of if its a thread or cluster
- I think, less duplicate code (we need to try this out)

## Cons

- Logic for Thread can not be shared
- Logic for Cluster can not be shared

![Fixed/Dynamic - Class Diagram](https://www.planttext.com/api/plantuml/img/ZP1D2i9034RtEKKk85wXqkBQXHU8Cq47Pbf8KgYtT_g36AdWCbzUtWTfr4XiB1d0acN6Sveu7hjdJoK5F62RIHMxH7UX0W1qKnCAXc5PdBRnCWnLiMQBOWwG9-C-Vb4hj3Kux7teJDU7CCKVe9Fja1yrJjhcKOtb7-iUwhHDZUe7Nm00)

**Comment by Shinigami92** [comment]
`Fixed/Dynamic - Class Diagram` doesn't work, because we would need to implement all these functions in thread and cluster dynamic pools

```ts
protected destroyWorker(worker: ThreadWorkerWithMessageChannel): void | Promise<void>;
protected isMain(): boolean;
protected sendToWorker(worker: ThreadWorkerWithMessageChannel, message: MessageValue<Data>): void;
protected registerWorkerMessageListener(port: ThreadWorkerWithMessageChannel, listener: (message: messageValue<Response>) => void): void;
protected unregisterWorkerMessageListener(port: ThreadWorkerWithMessageChannel, listener: (message: MessageValue<Response>) => void): void;
protected createWorker(): ThreadWorkerWithMessageChannel;
protected afterWorkerSetup(worker: ThreadWorkerWithMessageChannel): void;
```

That's even more then just `chooseWorker`

I will try another idea...

**Comment by Shinigami92** [comment]
Maybe the best solution would be to use something like `mixins`  
But I'm afraid 😱 and we should not do that!

**Comment by pioardi** [comment]
@Shinigami92  @jerome-benoit  I was thinking that we could just write chooseWorker as an utility an use the bind function before to use it

**Comment by Shinigami92** [comment]
> @Shinigami92 @jerome-benoit I was thinking that we could just write chooseWorker as an utility an use the bind function before to use it

Yes, this could be a solution
But then we need to do this also for the abstract `chooseWorker` implementation
Because this is accessed via `super.chooseWorker()`

So we have stacked strategies that can fallback in each other

We could also then rename it to `roundRobinSelection` or similar

**Comment by jerome-benoit** [comment]
The three PRs: 
+ https://github.com/pioardi/poolifier/pull/176
+ https://github.com/pioardi/poolifier/pull/191
+ https://github.com/pioardi/poolifier/pull/210 
stacked offer a rather clean API and implementation for worker choice algorithms and a new algorithm: less used worker.
It still lacks some unit tests but that can be tackled after as well as benchmarks.
