### ISSUE TITLE
Logo gets squashed on small display sizes

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#196]
**Describe the bug**
Logo gets squashed on small mobile display sizes.

**Steps to reproduce the behavior**
Navigate with your phone or via browser in mobile view to GitHub or NPM and visit poolifier.

**Expected behavior**
Logo should always have correct aspect ratio.

**Screenshots**

<img src="https://user-images.githubusercontent.com/7195563/108472437-07b21a80-728d-11eb-9660-76b5d0af3d21.png" width="200px"/>

**Comment by pioardi** [comment]
A bug is a code unexpected behaviour, we could find another tag for this kind of issues :)
