### ISSUE TITLE
Poolifier was not tagged as beta in npm

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#197]
**Describe the bug**
While publishing the newest `2.0.0` of poolifier, it seems that tagging was not.
This is potentially dangerous for our community.

Sadly this bug is NOT fixable anymore because you cannot delete versions from NPM :slightly_frowning_face:  
It can only be fixed when releasing the next `latest` real non-pre-release

But for the future we definitely should not publish beta releases into the latest tag anymore :warning: 

**Steps to reproduce the behavior**

When using e.g. `npm install poolifier` in a project, the current `latest` version of poolifier will be installed.
As can be seen here https://www.npmjs.com/package/poolifier on the versions tab, this is currently `2.0.0-beta.4`

**Expected behavior**

Tagging should have been used to produce tagged versions like in this project

![image](https://user-images.githubusercontent.com/7195563/108473693-a68b4680-728e-11eb-8576-c7e19937f2a8.png)

**Screenshots**

https://user-images.githubusercontent.com/7195563/108474457-b7888780-728f-11eb-99b7-ebe51167c45c.mp4

**Info**

| Tool      | Version       |
| --------- | ------------- |
| Poolifier | v2.0.0-beta.4 |

**Additional context**

- https://docs.npmjs.com/cli/v6/commands/npm-publish
- https://docs.npmjs.com/about-semantic-versioning
- https://docs.npmjs.com/cli/v6/using-npm/semver#prerelease-tags

**Comment by pioardi** [comment]
@Shinigami92  I got it, I don't think is really so problematic for users. 
This is anyway a breaking version, but if you would like to change this behavior please contribute to our github action for releases.

Semantic versioning is about versions so this is not a big issue IMO

**Comment by Shinigami92** [comment]
I don't know how to release via GitHub Actions
I only trust myself with human eyes checking the output that will be produced
So I always create releases manually for my Open Source projects

The semver part was just additional sources, nothing wrong with that

At least npm detects it as latest prerelease and humans can see that it is a beta that was installed when checking their `package.json`

**Comment by Shinigami92** [comment]
Since you had seen it now and received sufficient attention, I close the issue now ^^

**Comment by pioardi** [comment]
FYI This is our github action that is triggered when a github release is created : 

https://github.com/pioardi/poolifier/blob/master/.github/workflows/npmpublish.yml

So if you feel is so needed we can check the package.json version and if alpha or beta are presents you can add the tag explicitly.
I have no too much worries about that, same tag or not, the version is beta and users know what a beta release is.

**Comment by Shinigami92** [comment]
`[...] users know [...]`
and this is exactly the problem :warning: 
"machines don't know"

Some may have setup CI/CD that depends on `latest`

**Comment by Shinigami92** [comment]
I may not have much time today, hopefully over the weekend

**Comment by pioardi** [comment]
Not a problem, we can figure out how to handle this better later :)
