### ISSUE TITLE
pool maybe undefined

### ISSUE THREAD

**Issue by vorticalbox** [pioardi/poolifier#294]
**Describe the bug**
when defining  pool types say it can be undefined 

```
const pool = new FixedClusterPool(2,
  './dist/helpers/processReport.js',
  { errorHandler: (e) => console.error(e), onlineHandler: () => console.log('worker is online') });

pool.emitter.on('busy', () => console.log('Pool is busy'));
```

**Expected behavior**
types shouldn't be possibly undefined 

**Screenshots**
![image](https://user-images.githubusercontent.com/10886065/112524506-d058f100-8d97-11eb-96ac-c7213b9652fc.png)

**Info**

| Tool      | Version       |
| --------- | ------------- |
| Poolifier | v2.0.1       |
| Node      | v14.16.0     |
| OS        | ubuntu 20.04 |

**Additional context**
work is a ClusterWorker and async, wasn't an issue in v2.0.0

**Comment by Shinigami92** [comment]
So yeah it may be an undocumented breaking change, sorry for that

But indeed it is possible `undefined`, cause it is lazy initialized and not used by all pools

https://github.com/pioardi/poolifier/blob/c9170223028c20b8e47f6ef43d33cc5b8b68e07e/src/pools/pool-internal.ts#L50

So as a simple workaround you just should use e.g.

```ts
pool.emitter?.on('busy', () => console.log('Pool is busy'));
```
