### ISSUE TITLE
Considering support run async func in worker thread?

### ISSUE THREAD

**Issue by NeoyeElf** [pioardi/poolifier#30]
It seems that `ThreadWorker` can only accept sync function as args at present. What if provide an `options.async`, when it sets to be true, then exec async function.

example:
```
'use strict'
const { ThreadWorker } = require('poolifier')

async function yourFunction (data) {
  return new Promise((resolve, reject) => {
    resolve(1)
  })
}

module.exports = new ThreadWorker(yourFunction, { async: true, maxInactiveTime: 60000 })
```

**Comment by NeoyeElf** [comment]
#31

**Comment by pioardi** [comment]
Hi @NeoyeElf  , 
thanks to use poolifier and for your Pull Request .
I have one question , why should you use an async function into the thread pool ? 
I mean if your function is really async , maybe you will not need a thread pool for that...as per nodejs doc :   

Workers (threads) are useful for performing CPU-intensive JavaScript operations. They will not help much with I/O-intensive work. Node.js’s built-in asynchronous I/O operations are more efficient than Workers can be.

https://nodejs.org/api/worker_threads.html

Let me know your needed , if there is something that I miss on that I will consider this a valuable feature and we will add it to the project !!! Welcome :)

**Comment by NeoyeElf** [comment]
In my use case, I use [vm2](https://github.com/patriksimek/vm2) to run user's custom code(like [google app scripts](https://www.google.com/script/start/)). And the vm2 is not isolated, so I need to run in worker threads. And the script maybe contains async func.

Here is an example:
```
const { NodeVM } = require('vm2');
const { ThreadWorker } = require('poolifier')

async function execVM(data) {
  const vm = new NodeVM({
    require: {
      context: 'sandbox',
      external: false,
    },
    sandbox: {...someModules},
  });
  const exec = vm.run(`
    async function someAsyncFunc(args) {
      await requestSomeApi()
      doSomeCpuSensitive()
    }
  
    //... some other functions

    module.exports = {someAsyncFunc}
  `);
  return exec[data.func](data.args)
}

module.exports = new ThreadWorker(execVM, { maxInactiveTime: 60000, async: true })
```

**Comment by pioardi** [comment]
Thanks for your comment @NeoyeElf  , ok this is a feature to add . 
 I see that I should remove the coverage publish when the build run for a PR from a fork , I will fix that .
In the meanwhile please review your test case since that it is failing  on the last assertion https://github.com/NeoyeElf/poolifier/blob/ae2377d3db3c0d942a60770982ec0278cfe4cc3f/tests/fixed.test.js#L65

Thanks to use poolifier , you are welcome to contribute :)

**Comment by NeoyeElf** [comment]
the test case has been fixed

**Comment by pioardi** [comment]
Thanks @NeoyeElf  , I merged the PR , everything is fine .
I guess you will need a new version ( 1.1.0 ) of the library right ? :)

**Comment by NeoyeElf** [comment]
Yes. :)

**Comment by pioardi** [comment]
Version 1.1.0 is released , I will close this issue .
Let me know if everything is ok and thanks to contribute on this project !!!
