### ISSUE TITLE
module load err

### ISSUE THREAD

**Issue by NeoyeElf** [pioardi/poolifier#32]
My worker.js have require files which use [grpc lib](https://www.npmjs.com/package/grpc), and an error occurs when I start to run my program

> Error: Failed to load /path-to-my-work-space/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node. Module did not self-register: '/path-to-my-work-space/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node'.     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)\n     at Module.load (internal/modules/cjs/loader.js:977:32)\n     at Function.Module._load (internal/modules/cjs/loader.js:877:14)\n     at Module.require (internal/modules/cjs/loader.js:1019:19)\n     at require (internal/modules/cjs/helpers.js:77:18)\n     at Object.<anonymous> (/path-to-my-work-space/node_modules/grpc/src/grpc_extension.js:32:13)\n     at Module._compile (internal/modules/cjs/loader.js:1133:30)\n     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)\n     at Module.load (internal/modules/cjs/loader.js:977:32)\n     at Function.Module._load (internal/modules/cjs/loader.js:877:14)\n     at Module.require (internal/modules/cjs/loader.js:1019:19)\n     at require (internal/modules/cjs/helpers.js:77:18)\n     at Object.<anonymous> (/path-to-my-work-space/node_modules/grpc/src/client_interceptors.js:144:12)\n     at Module._compile (internal/modules/cjs/loader.js:1133:30)\n     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)\n     at Module.load (internal/modules/cjs/loader.js:977:32) 

any ideas? Is it possible that this error is related to the C++ addon using by [grpc lib](https://www.npmjs.com/package/grpc)?

**Comment by NeoyeElf** [comment]
it seems related to https://github.com/grpc/grpc-node/issues/778. I will try to replace the grpc to @grpc/grpc-js

**Comment by pioardi** [comment]
Ok , going to close the isse since it does not seems related to poolifier
