### ISSUE TITLE
unknown error when run async func

### ISSUE THREAD

**Issue by NeoyeElf** [pioardi/poolifier#33]
when I run my application, the error was catch by `pool.execute(...).then(...).catch(...)`:

```
Error:      at /data/node_modules/poolifier/lib/workers.js:67:19\\n     at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

any idea?

**Comment by pioardi** [comment]
Hi @NeoyeElf  , could you please indicate how to replicate the issue ?

**Comment by pioardi** [comment]
I need to replicate the issue so that I can help you to understand what is happening
Adding some logs before of the line 67 would help

**Comment by NeoyeElf** [comment]
I will try

**Comment by NeoyeElf** [comment]
I have add `console.log` just before the line 67

```
...
    fn(value.data).then(res => {
      console.log('!!!', res, value)
      this.parent.postMessage({ data: res, _id: value._id })
      this.lastTask = Date.now()
    })
...
```

Here is the output:
```
!!! {
  success: true,
  result: [
    { label: '嘿嘿嘿', type: '文本' },
    { label: 'time', type: '日期' },
    { label: '这是数字', type: '数字' }
  ],
  log: '_EMPTY_LOG_',
  status: 'success',
  execTime: 7263
} {
  data: {
    guid: 'EyV4MLkBNR',
    func: 'getFormItems',
    args: [],
    options: {
      source: "some string data",
      funcNames: 'some string data',
      context: [Object]
    }
  },
  _id: 2
}
```

Can't see anything wrong

**Comment by pioardi** [comment]
@NeoyeElf  please let me know how to replicate the issue so that I can help you

**Comment by NeoyeElf** [comment]
I figured it out. the real error is: (after I add error log before the [line 70](https://github.com/pioardi/poolifier/blob/master/lib/workers.js#L70))

```
_runAsync error DOMException [DataCloneError]: [object Object] could not be cloned.
    at /Applications/workspace/shimo/svc-sas-runner/node_modules/poolifier/lib/workers.js:67:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

and I print my return value `res` from worker:
```
{
  success: true,
  result: [
    { label: '嘿嘿嘿', type: '文本' },
    { label: 'time', type: '日期' },
    { label: '这是数字', type: '数字' }
  ],
  log: '_EMPTY_LOG_',
  status: 'success',
  execTime: 715
}
```

**Before I return the `res`, I add `res.result = JSON.stringify(result)`, then it works fine.**

My questions are:
1. Why my return value triggered this bug?
2. the error catch by `pool.execute` seems lack error.message, only contains the error.stack?

**Comment by pioardi** [comment]
Hi @NeoyeElf  ,
Glad to hear that you fixed the problem , logging always help !!! :) 
I would like to help you as best as I can and to do that I have to replicate the issue . 

Consider that worker thread and main thread communication is done via Buffers ( see https://nodejs.org/api/worker_threads.html#worker_threads_worker_threads ) .
For the error message we are passing all the error when we reject the execute Promise , so it should contain everything

**Comment by NeoyeElf** [comment]
> My questions are:
> 
> 1. Why my return value triggered this bug?
> 2. the error catch by `pool.execute` seems lack error.message, only contains the error.stack?

q1: It seems that something in the result returned by executing the func in vm2 triggered `DataCloneError `.  Never mind, I have solved it by using `JSON. stringify `

q2: I have verified the error message is complete

Thks @pioardi
