### ISSUE TITLE
How to exec a function on all the workers of my FixedThreadPool?

### ISSUE THREAD

**Issue by gitmalong** [pioardi/poolifier#448]
How can I execute a function on all the workers of my FixedThreadPool? For example to update a static attribute on each thread.

**Comment by jerome-benoit** [comment]
Hello, 

That's not really an issue for a bug ;) 

First you create your function in a separate file: https://github.com/pioardi/poolifier/blob/master/examples/yourWorker.js
Then you run it: https://github.com/pioardi/poolifier/blob/master/examples/fixedExample.js

**Comment by gitmalong** [comment]
Thanks for your reply @jerome-benoit . Indeed I already created a FixedThreadPool and spawned a fixet set of workers. I want to avoid the hustle of align my data structure to the SharedArrayBuffer so I just want to pass an object that my worker sets as static variable. That way I need to ensure to update that variable within every worker that was spawned before. 

I guess I could just iterate through the pools worker[] variable and call `runAsync`?

**Comment by jerome-benoit** [comment]
`runAsync` is protected in TS.

That will not permit to have static variable as shared. You can pass data to workers via the message channel interface but again, the data are not shared. Each work threads run in its own node.js processus and share nothing at all, like all processus. If you pass an object as `workerData` at `execute()`, the object lives its own life in the worker threads and nothing is shared, static attributes or not. 
There's only one way to share data between worker threads: `SharedArrayBuffer` and message channel.

Here are the an example of its encapsulation in `DataView` to track task usage in future poolifier version and ease access to it: 

```ts
/**
 * Shared object for workers tasks usage statistics.
 */
export class SharedUsage {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any
  private dataView: DataView

  /**
   * Create a shared object for workers tasks usage statistics.
   *
   * @param numberOfWorkers Number of workers.
   * @param sharedUsageArrayBuffer Shared array buffer to use to store workers tasks usage statistics.
   */
  constructor (
    private numberOfWorkers: number,
    sharedUsageArrayBuffer: SharedArrayBuffer
  ) {
    this.dataView = new DataView(sharedUsageArrayBuffer)
    for (
      let i = 0, startOffset = 0;
      i < this.numberOfWorkers;
      i++,
        startOffset +=
          3 * Int32Array.BYTES_PER_ELEMENT + Float64Array.BYTES_PER_ELEMENT
    ) {
      Object.defineProperty(this, `worker${i}-run`, {
        /**
         * Set worker `workerId` number of tasks run.
         *
         * @param value Number of tasks run.
         */
        set (value: number) {
          this.dataView.setInt32(startOffset, value)
        },
        /**
         * Get worker `workerId` number of tasks run.
         *
         * @returns Number of tasks run.
         */
        get (): number {
          return this.dataView.getInt32(startOffset)
        },
        configurable: true
      })
      Object.defineProperty(this, `worker${i}-running`, {
        /**
         * Set worker `workerId` number of tasks running.
         *
         * @param value Number of tasks running.
         */
        set (value: number) {
          this.dataView.setInt32(
            startOffset + Int32Array.BYTES_PER_ELEMENT,
            value
          )
        },
        /**
         * Get worker `workerId` number of tasks running.
         *
         * @returns Number of tasks running.
         */
        get (): number {
          return this.dataView.getInt32(
            startOffset + Int32Array.BYTES_PER_ELEMENT
          )
        },
        configurable: true
      })
      Object.defineProperty(this, `worker${i}-runTime`, {
        /**
         * Set worker `workerId` tasks run time.
         *
         * @param value Tasks run time.
         */
        set (value: number) {
          this.dataView.setInt32(
            startOffset + 2 * Int32Array.BYTES_PER_ELEMENT,
            value
          )
        },
        /**
         * Get worker `workerId` tasks run time.
         *
         * @returns Tasks run time.
         */
        get (): number {
          return this.dataView.getInt32(
            startOffset + 2 * Int32Array.BYTES_PER_ELEMENT
          )
        },
        configurable: true
      })
      Object.defineProperty(this, `worker${i}-avgRunTime`, {
        /**
         * Set worker `workerId` tasks average run time.
         *
         * @param value Average tasks run time.
         */
        set (value: number) {
          this.dataView.setFloat64(
            startOffset + 3 * Int32Array.BYTES_PER_ELEMENT,
            value
          )
        },
        /**
         * Get worker `workerId` average tasks run time.
         *
         * @returns Average tasks run time.
         */
        get (): number {
          return this.dataView.getFloat64(
            startOffset + 3 * Int32Array.BYTES_PER_ELEMENT
          )
        },
        configurable: true
      })
      this[`worker${i}-run`] = 0
      this[`worker${i}-running`] = 0
      this[`worker${i}-runTime`] = 0
      this[`worker${i}-avgRunTime`] = 0
    }
  }

  /**
   * Dump attributes for debugging purpose.
   */
  public consoleDump (): void {
    for (let i = 0; i < this.numberOfWorkers; i++) {
      console.debug(`worker${i}-run: ` + this[`worker${i}-run`])
      console.debug(`worker${i}-running: ` + this[`worker${i}-running`])
      console.debug(`worker${i}-runTime: ` + this[`worker${i}-runTime`])
      console.debug(`worker${i}-avgRunTime: ` + this[`worker${i}-avgRunTime`])
    }
  }
}

```

**Comment by gitmalong** [comment]
Thanks for the code and explanation. Yes, I'm aware of that I'm exchanging simplified data structures against higher memory usage.

Meanwhile I found a way to setup additional listeners to the worker:

```
    const pool = new FixedThreadPool(2, join(__dirname, 'my.worker.js')})
     // ... wait until workers are online

      for (const w of pool.workers) {
            w.port2.on('message', (a)  => {
                console.log("my listener 1: ")
                console.log(a)
            })
            w.port2.on('message', (a)  => {
                console.log("my listener 2: ")
                console.log(a)
            })
        }

```

But how to post a message?

**Comment by jerome-benoit** [comment]
`sendToWorker()` is protected in poolifier. The native node.js worker threads interface is https://nodejs.org/api/worker_threads.html#worker_threads_class_messagechannel

**Comment by gitmalong** [comment]
I tried the following within my loop but my msgs only receive the regular msgs from my function calls and not the 'fun' msg.

```
         w.port1.postMessage('fun port 1')
            w.port2.postMessage('fun port 2')
```

**Comment by jerome-benoit** [comment]
Read carefully the official documentation to understand how the message channel interface works. 

You can use poolifier pool methods `registerWorkerMessageListener()` to register a custom message listener on each worker and `sendToWorker()` if you are not using TS to avoid to play with the portX that you are not using properly.

**Comment by jerome-benoit** [comment]
> `sendToWorker()` is protected in poolifier for TS.  The native node.js worker threads interface is [nodejs.org/api/worker_threads.html#worker_threads_class_messagechannel](https://nodejs.org/api/worker_threads.html#worker_threads_class_messagechannel)

**Comment by gitmalong** [comment]
Thanks for your coaching @jerome-benoit ! Using `registerWorkerMessageListener()` and `sendToWorker()` solved my issue!
