### ISSUE TITLE
The DynamicThreadPool does not seem to revive new workers after they are killed

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#61]
We currently used DynamicThreadPool with min: 2, max: 8 workers.
The workers start with 2 worker and after we used several workers, they scale up to 8 as expected. (`maxInactiveTime`)
After 60 seconds of idle-time, they scale down and the `exit`-handler is fired. (`worker.on('exit', ...`)
But if we then request some new workers after they were killed, it seems they don't scale up to 8 again :thinking: 

We started to modified the code in node_modules and tried to just remove `worker` from `this.workers`, but it seems that this wasn't enough to let it know to respawn new workers after they were killed

https://github.com/pioardi/poolifier/blob/5806029f3bdc6bc31d8cc8a611f77f5f3d2c1c88/lib/dynamic.js#L44-L49

The `worker.on('online', ...` event wasn't fired again after the 8 workers scaled down to 2 and expected to re-scale up

I'm interested to help on this issue/bug, but currently you may know your code better and therefore could potentially identify the real problem more quickly

**Comment by pioardi** [comment]
Wow this Is really interesting, I am currently from my phone ( and a Little busy this week in general) , but I will try to replicate the issue and let you know ASAP

**Comment by pioardi** [comment]
So I replicated the issue and maybe I have a fix , I need a more deep test before to merge :

on the file dynamic.js , after the line 47 we need to add :

          const myIndex = this.workers.indexOf(worker)
          const removed = myIndex > -1 ? this.workers.splice(myIndex, 1) : false
          console.log(this.workers.length)

and we are done , I did a quick test and is working . Going to fix this as soon as I can and if you want to do a test or a PR on your own I would be really happy !!!!


Thanks to catch this !

**Comment by Shinigami92** [comment]
We have already tried this (maybe not well enough)
But I think this isn't enough, because the workers doesn't scale up again
Seems to have to do something with

https://github.com/pioardi/poolifier/blob/5806029f3bdc6bc31d8cc8a611f77f5f3d2c1c88/lib/dynamic.js#L38

And `tasks`

https://github.com/pioardi/poolifier/blob/5806029f3bdc6bc31d8cc8a611f77f5f3d2c1c88/lib/dynamic.js#L27

So I think we also need to clean the workers from the `tasks` map
This we havn't tried yet

**Comment by pioardi** [comment]
Yes I guess we are near to fix it , I did a quick and basic test but seems to work properly it start from 2 , then go to 8 , then on 2 and then to 8  and so on...

For the tasks map , would be good to clean the entry but is not mandatory , I will do that anyway to clean the memory :)

**Comment by pioardi** [comment]
@Shinigami92  I fixed this issue and added a unit test about this , use the version 1.2.1 and see if works well also for you.
I will keep this open for today, hoping you are able to take your test today :) 
Thank you much to catch this issue , I wanted to fix it as soon as I can .

Note: For the other issues I will need a little more time

**Comment by Shinigami92** [comment]
Thank you and yes I will try to test it today but today is meeting day :wink:, so maybe I don't find the time within working hours
So could be late or could be tomorrow

I will look into your (code-)changes right now :eyes: and do a kinda review :cat:

**Comment by pioardi** [comment]
Thanks @Shinigami92  , I would like to connect with you on linkedin ( I post something on poolifier sometimes there )

**Comment by Shinigami92** [comment]
Sorry I don't have `LinkedIn` :sweat_smile:  
But if you want contact me outside of GitHub, you can see some possibilities in my GitHub profile like Twitter or EMail

**Comment by Shinigami92** [comment]
Test will more be tomorrow :slightly_frowning_face:, sorry

**Comment by pioardi** [comment]
Is ok, take your time :)

**Comment by Shinigami92** [comment]
We at adSoul are happy to inform you that everything is working now :tada:
