### ISSUE TITLE
Use prettier

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#63]
I would like to implement the use of prettier, so when I'm working with the code, I don't need to run commands like `yarn standard --fix` and just use `Format on save` in VSCode

I'm interested to create a PR for that

**Comment by pioardi** [comment]
Hi @Shinigami92  thanks a lot for all your feedbacks on poolifier.
So, prettier is only code formatting where standard is also about best( or I should say standard ) practices into the code.

I would like to keep standard on the repo, I Will keep this issue open so we can discuss further :)

Thanks again

**Comment by Shinigami92** [comment]
Current problem was, I forked the repo and pressed `Ctrl+S` and this auto-formatted the code in my VSCode and completely destroys the current wanted format
If prettier is configured, this wont happen
Prettier can be configured to produce `standard` formatted code
Also `standard` can still be used further alongside prettier

**Comment by pioardi** [comment]
Got It , seems that something like https://www.npmjs.com/package/prettier-config-standard can help us?
So we can keep standard and use prettier without impact

**Comment by Shinigami92** [comment]
Mh today I tried a run with prettier
But especially the `space-before-function-paren` is not really possible with prettier
Maybe I could try [`prettierx`](https://github.com/brodybits/prettierx), but maybe it would be better to just setup your repo with a `.vscode/settings.json` + extension recommendation for [vscode standardjs](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs)
Then we need to configure `ts-standard` for TS later on

I personally really like prettier, but if you want standard in your repo, prettier seems not a good choice for this repo 😕

Yes, prettier needs some more config setup as standard, but I prefer it cause IMO it's more human readable and stronger :man_shrugging:  
Also prettier is much more used out there: https://www.npmtrends.com/prettier-vs-standard

**Comment by pioardi** [comment]
Hi @Shinigami92, standard and prettier are two different things with two different targets.
Prettier is a code formatter, standard is a style guide.


This project https://github.com/sheerun/prettier-standard , seems to be what we need and I see that different node projects use both prettier and standard, we just need to figure out how.

I will take a look as fast as I can :)

**Comment by Shinigami92** [comment]
![image](https://user-images.githubusercontent.com/7195563/99155104-58760e00-26b5-11eb-9811-31c90693fc25.png)

😜

This tool just wraps the things I would configure manually ^^

At least for me: the TypeScript support is much more important to work with the code, then the formatting and style-guide

**Comment by pioardi** [comment]
I am going to try something on this next week

**Comment by pioardi** [comment]
Dear @Shinigami92,
hope you are doing well and you year started well. I take a lot of time for this small thing and I apologies for that :)
On this new branch https://github.com/pioardi/poolifier/tree/feature/prettier , you should be able to use prettier and standard together :) Could you take a test and let me know?

**Comment by Shinigami92** [comment]
Hi @pioardi, thanks, hope you doing well also.  
I will try it tomorrow :slightly_smiling_face:

**Comment by Shinigami92** [comment]
So I checked out the branch and made safe that I reloaded VSCode and have installed everything with yarn correctly
Then I went into a file like `dynamic.js` and pressed `Ctrl+S`
The auto-formatted result differs in using:
- double quotes instead of single
- adding semicolons
- removing the space between method-name and brace

Example: 
![image](https://user-images.githubusercontent.com/7195563/104715995-89130c00-5727-11eb-8f26-711ce0c0bb91.png)

_But I already find the code more readable than before_ :sweat_smile: (I mean branch `feature/prettier` vs `master`)

---

I added a file `.prettierrc.json` in the root and configured it with:
```jsonc
{
  "arrowParens": "avoid",
  "semi": false,
  "singleQuote": true,
  "spaceBeforeFunctionParen": true, // <-- doesn't work :(
  "trailingComma": "none"
}

```

After that only the spaces between method-name and opening braces are removed and the rest was okay.
~So maybe you only need prettierx now to get benefit of `space-before-function-paren`?~

:thinking: `prettier-standard` already uses `prettierx`
So maybe `prettierx` doesn't get correctly called because the VS Code [extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) doesn't support it?
Also this extension is by far the most downloaded prettier extension for VS Code :eyes:
Maybe it would be okay for you not to insist on `spaceBeforeFunctionParen`? Would this be an option for you?

Or we could open an issue in the repo of this extension... -> Look what I have found :laughing: https://github.com/prettier/prettier-vscode/issues?q=prettierx

**Comment by pioardi** [comment]
Oh wow, nice job @Shinigami92  , so we now just need  to figure out how to   "spaceBeforeFunctionParen": true.
I will check if standard task will fail in case there is no space, if it does not fail we can also go ahead in this way

**Comment by pioardi** [comment]
@Shinigami92  I was thinking that we can just write to run "npm run lint" that will format(with prettier) and lint the code(with standard) in our contribution guidelines and we should be ok, what you think about this ?

Please let me know I feel this could be a great way that will enable contributors to use both prettier and standard and we have done.

**Comment by Shinigami92** [comment]
This should be fine for the first step.
But maybe in the future we can improve this with something like commit hooks.
But I'm not familiar with installing hookes, and if it's set up incorrectly it can break PRs and fear contributors :slightly_frowning_face:

**Comment by pioardi** [comment]
Yes so currently any commit on any branch will run a GitHub action with this command "npm run tests".
For some reason this is not fully working when the branch is a fork ( but is another story, I will look into that soon ).
So let's close the issue and merge the branch :)
