### ISSUE TITLE
Dynamic thread pool exiting after maxInactiveTime for long running jobs

### ISSUE THREAD

**Issue by jithinsk** [pioardi/poolifier#70]
I have a job running for more than one minute (it involves some API calls). The issue is that after one minute (default maxInactiveTime), the worker will close itself whether the job is running or not. I think the code should include a check for whether the job is running or not in function `_checkAlive`.
Please share your thoughts on this.

As a workaround for now, I can either move to Fixed thread pool or use a high value for maxInactiveTime.

**Comment by pioardi** [comment]
Hi @jithinsk ,
first of all nice to meet you and thanks to use this library.
So the behaviour that you described is expected, the code do not check if the thread is working on something or not, I think you can just increase the maxInactiveTime.

I will check if there is an easy and clean way to check if a task is in progress or not and let you know, you can even contribute on this with ideas or a PR if you desire :)

**Comment by jithinsk** [comment]
Thanks for the quick reply, I need a quick solution, so I will go with high value for maxInactiveTime for now. I will surely look into contributing in my free time.

**Comment by Shinigami92** [comment]
@pioardi What do you think about to provide the option to set the `maxInactiveTime` to `Infinity` or `-1` and then check if this was set and if so don't check the alive state.
So it will run for ever.
Then you can destroy a worker e.g. with the help of `destroyWorker` on your own.
So give the developer the possibility to manage they pool on their own.

**Comment by pioardi** [comment]
Infinity Is maybe already an option( or anyway to set maxInactiveTime really High).
I would not give the possibility to manage workers, what we can do is track if a worker has any active task and in this case we should not destroy It.

I would give the option to enable or not this tracking since can be not mandatory in a lot of cases.

Should be also easy to implement since se know when a task start and complete

**Comment by pioardi** [comment]
This tracking strategy should foto well for long running task and we can give general guidance to enable It if the task is long running or not predictable 😁

**Comment by Shinigami92** [comment]
The only _problem_ with setting it to `Infinity` is that it always checks and recalculates the alive. This is not needed if intentionally set to `Infinity`

**Comment by pioardi** [comment]
If you set It to infinity your pool would be Just Like a fixed thread pool at a point in time

**Comment by Shinigami92** [comment]
You are right... :thinking:

**Comment by pioardi** [comment]
@jithinsk just to inform you that I have something draft and that most likely fixes this.
Most likely the new behavior will check the number of active tasks( no configuration needed, this will be checked always) and if any task is active the worker will not be stopped.

This should improve the general behaviour and helps you with your long running job.
The new code will be available on the poolifier version 2.x.x, but if you have any urgency we could work to do a bug fix on version 1.x.x. 

pioardi

**Comment by jithinsk** [comment]
@pioardi That's great to hear. The high value for maxInactiveTime is working well in my use case now. I will update when the new version is released. Thanks for picking this up and solving this.

**Comment by pioardi** [comment]
You are welcome @jithinsk and thank you to open this issue and to use poolifier, I suggest you to look at the PR linked to this issue would be useful if you want to contribute in future.

If I can ask, for what are you using poolifier? :)

**Comment by jithinsk** [comment]
Yeah sure.
Our use case was basically scraping, with some operations on scrapped data. 
The operations has some legacy code and was taking some time. Also we wanted to isolate each task to reduce failures.
So as a quick fix, I moved to a thread based system with a queue before poolifier. This has improved system responsiveness for us.

**Comment by pioardi** [comment]
Great hopefully this library helped you.
Look for new release, on the version 2.0.0 version this will be fixed :)

**Comment by pioardi** [comment]
@jithinsk  FYI we released a 2.0.0.beta version that you can now use.
We will release the 2.0.0 stable version around next week.
Enjoy :)
