### ISSUE TITLE
Version 2.0.0 Contribution

### ISSUE THREAD

**Issue by pioardi** [pioardi/poolifier#8]
If you want to join the project , you can find some tasks here https://github.com/pioardi/poolifier/projects

**Comment by klevison** [comment]
Congrats for all lib, but "Typescript support" needs to be the most important issue :)

**Comment by pioardi** [comment]
Hi @klevison  , thanks much and yes I agree that typescript support is the most important feature to have .

Are you interested to contribute on that ?

**Comment by NeoyeElf** [comment]
It seems [Async Hooks](https://nodejs.org/docs/latest-v12.x/api/async_hooks.html) is an Experimental feat...Considering replace it with something else? or just remove it?

**Comment by pioardi** [comment]
Hi @NeoyeElf  , 
I am aware that async hooks are a preview feature , but from node js is highly recommended to use them if you implement a thread pool...so for now I guess is the better option to leave them here

**Comment by NeoyeElf** [comment]
Get it @pioardi

**Comment by pioardi** [comment]
I will close the issue to increase maintenance score on npmjs , anyway any contributions or question is welcome
