### ISSUE TITLE
Update Changelog for v2.0.0

### ISSUE THREAD

**Issue by Shinigami92** [pioardi/poolifier#89]
@pioardi Do not forget to update the changelog before bundling the new major release :wink: 
This is just a reminder issue, because who needs papers lol

**Comment by Shinigami92** [comment]
@pioardi https://github.com/pioardi/poolifier/pull/86#issuecomment-775390339

You could also potentially look at the https://github.com/pioardi/poolifier/projects/1 board and then create changelog-entries based on that

**Comment by Shinigami92** [comment]
The _problem_ is that I don't know how **you** want your changelog messages :smile:

**Comment by pioardi** [comment]
Yes we need to define that, maybe we can just add a short description of the task worked.
But what we could really want is a migration guide that explain to end users how to migrate from a 1.x.x. version to a 2.x.x version.....

**Comment by Shinigami92** [comment]
But for that, we need to know what will be added in e.g. #88 and #66 
And that's why we need to bundle the changelog at the end when everything is kinda finished

**Comment by pioardi** [comment]
I think we can close this issue since that we are adding any relevant change to the changelog for any PR.
Maybe we could add this recommendation to the contributing.md

**Comment by Shinigami92** [comment]
I would prefer to close this issue when we have bundled everything together

As the description points our, this is a reminder issue
So we don't forget anything

We can add a TODO-list in this issue if you want

**Comment by pioardi** [comment]
Into our 2.x.x release note we will add:

*** Breaking Changes***

*** New features ***
Cluster pools( pools of processes) are now available and you can use it in combination with thread pools (we still need to write examples)
Other features that we will work on 

General enhancements

- Project written in typescript, this should also increase the performance
- Enhancement on internal code and variable names
- Add static code analysis with Sonar, and changed coveralls in favor of Sonar, this also covers security
- Procution code minification for production to increase performances
- Added unit test cases
- Community readiness, we have more active contributors and  open source community standards

**Comment by pioardi** [comment]
I was thinking that due to the way how npm scores the project maintenance, we should close this issue since Is not really an issue but a placeholder.
I will pin this issue into the dashboard for now.

**Comment by Shinigami92** [comment]
We need to remember to remove the `not released yet`
And we need to document the #176 strategies and newly public member functions

**Comment by pioardi** [comment]
@jerome-benoit  @Shinigami92  I would like to release the 2.0.0 stable version next week, so if you could please write a little of documentation on selection strategies before that would be much much appreciated.
I have almost everything ready articles,social posts and so on. We still would need a little more coverage ( on selection strategies I think is the only poin where we can do that easily ) and I would also re-introduce the .npmignore as I explained into a discussion.

We are close to this release guys !!!! I am so happy to share with our network what we are doing !!!!

**Comment by jerome-benoit** [comment]
I do not think I will be able to do it that week. Coverage on selection strategies files is 100%. 
You've closed the PR amending the documentation and I think you should not have. 
If you just restructure a bit what you wrote, that will be enough.

**Comment by pioardi** [comment]
> I do not think I will be able to do it that week. Coverage on selection strategies files is 100%.
> You've closed the PR amending the documentation and I think you should not have.
> If you just restructure a bit what you wrote, that will be enough.

Hei Jerome, which PR have we closed ? Was about documentation or contained other stuff also ? 

Lines are 100%, branches are not around 85%
<img width="833" alt="Schermata 2021-02-24 alle 14 34 04" src="https://user-images.githubusercontent.com/15161576/109008239-602e5100-76ad-11eb-9538-df6e84be465d.png">

**Comment by jerome-benoit** [comment]
https://github.com/pioardi/poolifier/pull/233

**Comment by pioardi** [comment]
> #233

So I closed that because that was on general guidance documentation not on strategies doc.
General guidance can still be improved but I feel we can go ahead as we are for now.
Strategies are not documented at all so for end user are really difficult to choose and use.

**Comment by jerome-benoit** [comment]
The PR added important information on cluster worker vs. worker-threads that are currently missing. 
Like I said on the PR, you can make your text more light but the content really make things clearer: the add of cluster worker done by @Shinigami92 is the main feature of version 2.0.0. 
Strategies can stay a bit hidden at the beginning of the 2.x.x release cycle: there's only one more strategy and I'm not very happy with the implementation I've made on that one (it was enough for testing purpose). 
The goal was to provide a pluggable code encapsulation for worker selection strategy as light and clean as possible. I think that part is almost done (the untangling PR will make things really cleaner). 
The next part is to make the strategies selection code really efficient.  
So if 2.0.0 does not talk about the glory details on existing strategies, I do not think that's important, the default one really works well. Just mentioning the existence of the pluggable framework should be enough.

**Comment by pioardi** [comment]
Got it sounds good about the strategies I can just say that we introduced worker selection strategies.
For the general guidance we still have a branch and can continue on that

**Comment by Shinigami92** [comment]
> Lines are 100%, branches are not around 85%
> <img alt="Schermata 2021-02-24 alle 14 34 04" width="833" src="https://user-images.githubusercontent.com/15161576/109008239-602e5100-76ad-11eb-9538-df6e84be465d.png">

We cannot test some of these branches because they are not reachable from tests
We would need to export the functions for that so we could unit test them
But IMO it's ok to leave it just this way it is currently
